import type { FieldSpec } from '../schema-spec.js'
import type { Fixture, Technique, Validity } from '../types.js'

const UNBOUNDED_PROBE_LENGTH = 10_000

/** A benign, valid, distinct element for filling an array of the given item type. */
function benignElement(items: FieldSpec, i: number): unknown {
  switch (items.type) {
    case 'string': {
      let s = String.fromCharCode(97 + (i % 26))
      if (i >= 26) s += String(i) // keep every filler distinct past 'z' (uniqueItems, unbounded)
      const min = items.minLength ?? 0
      if (s.length < min) s = s.padEnd(min, 'x')
      const max = items.maxLength
      if (max !== undefined && s.length > max) s = s.slice(0, max)
      return s
    }
    case 'number':
    case 'integer': {
      const base = items.minimum ?? 0
      let v = base + i
      if (items.maximum !== undefined && v > items.maximum) v = items.maximum
      return items.type === 'integer' ? Math.trunc(v) : v
    }
    case 'boolean':
      return i % 2 === 0
    case 'enum': {
      const members = items.enumValues ?? []
      return members.length > 0 ? members[i % members.length] : `item-${i}`
    }
    default:
      return `item-${i}`
  }
}

/**
 * Adversarial values for an array field, along two axes: length (Boundary Value
 * Analysis on minItems / maxItems, the empty array, and an unbounded-length
 * probe) and element (each element-type adversarial value carried into a single
 * slot of an otherwise legal array). Uniqueness, sparse holes, and array-like
 * duck-typing round it out.
 *
 * `childFixtures` is the same dispatch the top-level fields use, so an element
 * is generated by exactly its own type's rules - an enum element yields
 * out-of-set, a string element yields the hostile catalog, and so on.
 */
export function arrayFixtures(field: FieldSpec, childFixtures: (f: FieldSpec) => Fixture[]): Fixture[] {
  const out: Fixture[] = []
  const items = field.items ?? { name: '', type: 'unknown', required: true }
  const { minItems, maxItems, uniqueItems } = field

  const fill = (len: number): unknown[] => Array.from({ length: len }, (_, i) => benignElement(items, i))

  // The benign filler satisfies plain scalar and enum element types, but it cannot
  // guarantee a value that meets an element format/pattern (e.g. array-of-email) or an
  // element that is itself a union/array/unknown. In those cases a legal-length array is
  // only 'unknown', not 'valid', because its elements may still fail the element check.
  const fillerCertain =
    items.type === 'number' ||
    items.type === 'integer' ||
    items.type === 'boolean' ||
    items.type === 'enum' ||
    (items.type === 'string' && items.format === undefined && items.pattern === undefined)
  const legalLengthValidity: Validity = fillerCertain ? 'valid' : 'unknown'

  const push = (value: unknown, technique: Technique, family: string, note: string, valid: Validity): void => {
    out.push({ field: field.name, value, technique, family, failureHypothesis: note, valid })
  }

  // -- Length (BVA) --------------------------------------------------------
  push(
    [],
    'BVA',
    'empty',
    'Empty array. The most-forgotten collection input: probes required-vs-optional handling, reduce() with no initial value (which throws on an empty array), first-element destructuring, and any render-the-results path that assumes at least one element.',
    minItems !== undefined && minItems >= 1 ? 'invalid' : 'valid',
  )

  if (minItems !== undefined) {
    if (minItems - 1 > 0) {
      push(
        fill(minItems - 1),
        'BVA',
        'below-min-items',
        `One element short of minItems (${minItems}). If a length guard is missing or uses the wrong comparator (> vs >=), an under-sized collection slips through to code that assumes the minimum count is present.`,
        'invalid',
      )
    }
    if (minItems >= 1) {
      push(
        fill(minItems),
        'BVA',
        'at-min-items',
        `Exactly minItems (${minItems}), the lower boundary. Probes an off-by-one guard that wrongly rejects the smallest legal collection.`,
        legalLengthValidity,
      )
    }
  }

  if (maxItems !== undefined) {
    if (maxItems >= 1) {
      push(
        fill(maxItems),
        'BVA',
        'at-max-items',
        `Exactly maxItems (${maxItems}), the upper boundary. Probes an off-by-one guard that wrongly rejects the largest legal collection, and batch or pagination code sized to exactly the limit.`,
        legalLengthValidity,
      )
    }
    push(
      fill(maxItems + 1),
      'BVA',
      'above-max-items',
      `One element over maxItems (${maxItems}). If the cap is enforced only in the UI or not at all, an over-sized collection reaches storage or a bulk operation whose size the backend assumed was bounded.`,
      'invalid',
    )
  } else {
    push(
      fill(UNBOUNDED_PROBE_LENGTH),
      'BVA',
      'unbounded-length',
      `No maxItems is declared. A ${UNBOUNDED_PROBE_LENGTH}-element array probes O(n^2) handling (nested loops, repeated includes/indexOf) that can turn into a denial of service, request-body size limits, and bulk-insert or IN (...) parameter caps at the storage layer.`,
      'unknown',
    )
  }

  // -- Element hazard: carry each element-level adversarial value into one slot.
  if (maxItems !== 0) {
    const len = Math.min(Math.max(minItems ?? 1, 1), maxItems ?? Infinity)
    for (const child of childFixtures(items)) {
      if (child.valid === 'valid') continue // a valid element in a legal array is not adversarial
      const arr = fill(len)
      arr[0] = child.value
      push(
        arr,
        child.technique,
        `element-${child.family}`,
        `Legal array length, but one element carries an element-level hazard: ${child.failureHypothesis} Probes validators that check the collection's shape and length yet never validate each element.`,
        child.valid,
      )
    }
  }

  // -- Uniqueness (only meaningful when uniqueItems is declared) ------------
  if (uniqueItems === true) {
    const zeroInRange =
      (items.minimum === undefined || items.minimum <= 0) && (items.maximum === undefined || items.maximum >= 0)
    if ((items.type === 'number' || items.type === 'integer') && zeroInRange) {
      push(
        [0, -0],
        'EP',
        'duplicate-items',
        'uniqueItems is declared but a duplicate is present. For the 0 / -0 pair the layers disagree on the value itself, not just equality: Object.is(-0, 0) is false in memory, but JSON.stringify(-0) yields "0", so [0, -0] serializes to [0, 0] and the two elements collapse to an identical pair the moment the array crosses a JSON boundary.',
        'invalid',
      )
    } else {
      const dup = benignElement(items, 0)
      push(
        [dup, dup],
        'EP',
        'duplicate-items',
        'uniqueItems is declared but a duplicate is present. Probes whether uniqueness is actually enforced or only documented: a check built on a JS Set dedupes the pair, but a missing check lets the duplicate reach storage where a unique index then rejects it.',
        'invalid',
      )
    }

    if (items.type === 'unknown' || items.type === 'array') {
      push(
        [{ k: 1 }, { k: 1 }],
        'EP',
        'structural-duplicate',
        'uniqueItems is declared and the two elements are deep-equal but distinct object references. A uniqueness check built on a JS Set keys by reference, so it counts them as different and passes, while JSON Schema uniqueItems and a database unique constraint compare by value and reject. Probes whether uniqueness is enforced structurally or only by identity.',
        'invalid',
      )
    }
  }

  // -- Sparse hole ---------------------------------------------------------
  const sparseLen = Math.min(Math.max(minItems ?? 2, 2), maxItems ?? Infinity)
  if (sparseLen >= 2) {
    const sparse = fill(sparseLen)
    delete sparse[1]
    push(
      sparse,
      'EP',
      'sparse-array',
      'A sparse array with a hole. map/forEach/filter skip holes while length still counts them, JSON.stringify serializes a hole as null, and spread or Array.from materialize it as undefined, so element count, per-element validation, and serialization disagree about what the array contains.',
      'unknown',
    )
  }

  // -- Array-like duck-typing (a non-array where an array is expected) ------
  push(
    { 0: benignElement(items, 0), length: 1 },
    'EP',
    'array-like-object',
    'An array-like object, not a real array. Array.isArray returns false, yet value.length reads 1 and value[0] is set, so a validator that duck-types on .length or indexes positionally instead of calling Array.isArray accepts a non-array that later throws when code calls .map / .filter / .push.',
    'invalid',
  )

  return out
}
